### ISSUE TITLE
Scraping empty csv files

### ISSUE THREAD

**Issue by mezasr** [kshvmdn/nbadrafts#1]
I came across this issue when attempting to run `create_csv.py` for the 2016 and 2017 drafts.

Using Python 3.4:
![keyerror](https://user-images.githubusercontent.com/4485689/40177811-96669d06-59ad-11e8-99ea-4e692dbc6009.png)

The KeyError leads me to believe it's trying to index an empty `draft` object. I removed the index and the script ran successfully but produced an empty csv file with no stats from the draft's web page. This, in fact, occurs for any draft year going back to 1947. The script replaced all the csv files in the datasets directory (containing the correctly scraped stats) with empty files.

Unless basketball-reference.com changed the way they publish their data, I don't see why the script shouldn't work. Does `draft_scraper.py` need to be modified?

**Comment by kashav** [comment]
Hey @mezasr - thanks for letting me know about this!

There was indeed a slight change in the HTML structure on the draft pages, which was causing the scraper to fail.

I pushed a fix, so the scraper should work as intended now.

**Comment by mezasr** [comment]
Great!
